
import '../../LoginMode.dart';
abstract class repo{
  Future<List>?getAll(String t);
  Future<void>?postAll(Autogenerated autogenerated);
  Future<void>?UpdateAll();
  Future<void>?deleteAll();


}

