import 'dart:convert';

import 'package:hospital/Network/dio/repo.dart';
import 'package:http/http.dart'as http;

import '../../LoginMode.dart';
import '../../constant.dart';
class api extends repo{
  @override
  Future<void>? UpdateAll() {
    // TODO: implement UpdateAll
    throw UnimplementedError();
  }

  @override
  Future<void>? deleteAll()async {
    try{
      http.Response response=await http.delete(Uri.parse(user_url),body: jsonEncode(Autogenerated().toJson()));
      print(response.body);
    }catch(e){
      print(e);
    }
  }

  @override
  Future<List>? getAll(String t) async{
    List? body;
    try{
      http.Response response=await http.get(Uri.parse(t));
      if(response.statusCode==200){
        body=jsonDecode(response.body);
      }
    }catch(e){
      print(e);
    }
    return body!;
  }

  @override
  Future<void>? postAll(Autogenerated autogenerated)async {
    try{
      http.Response response=await http.post(Uri.parse(user_url),headers: {"Content-type": "application/json"},body: jsonEncode(Autogenerated().toJson()));
      print(response.body);
    }catch(e){
      print(e);
    }
  }


}