String user_url="https://stark-lake-52973.herokuapp.com/hospital/";
String ?id;
String?recid;
String ?pid;
String patient_url="https://stark-lake-52973.herokuapp.com/patient/";
String Doctor_url="https://stark-lake-52973.herokuapp.com/doctor/";
String Nurse_url="https://stark-lake-52973.herokuapp.com/nurse";
String Shu_url="https://stark-lake-52973.herokuapp.com/dpatient";
String NShu_ul= "https://stark-lake-52973.herokuapp.com/npatient";
String shu="https://stark-lake-52973.herokuapp.com/dpatient/schedule/";
String record="https://stark-lake-52973.herokuapp.com/medicalrecord/";