class Autogenerated {
  String? sId;
  String? password;
  String? name;
  String? address;
  String? phone;
  String? departments;
  int? iV;

  Autogenerated(
      {this.sId,
        this.password,
        this.name,
        this.address,
        this.phone,
        this.departments,
        this.iV});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    password = json['password'];
    name = json['name'];
    address = json['address'];
    phone = json['phone'];
    departments = json['departments'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['password'] = this.password;
    data['name'] = this.name;
    data['address'] = this.address;
    data['phone'] = this.phone;
    data['departments'] = this.departments;
    data['__v'] = this.iV;
    return data;
  }
}